default: &default
  adapter: sqlite3
  database: spec/test.db

sqllite:
  <<: *default

postgres:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: trax_model_test
  pool: 5
  host: localhost
  username: postgres
  password:
