default: &default
  adapter: sqlite3
  database: spec/test.db

sqllite:
  <<: *default

postgres:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: trax_model_tests
  pool: 5
  host: <%= ENV['DATABASE_URL'] || 'localhost' %>
  username: postgres
  password:
